packages:
  - 'packages/*'
  - 'docs'
  - 'e2e'

overrides:
  yjs: 13.6.29

allowBuilds:
  esbuild: true
  '@playwright/test': true
  '@biomejs/biome': false

patchedDependencies:
  '@hocuspocus/server@4.6.0': patches/@hocuspocus__server@4.6.0.patch
