packages:
  - 'packages/*'
  - 'docs'
  - 'e2e'

overrides:
  yjs: 13.6.29

allowBuilds:
  esbuild: true
  '@playwright/test': true
  '@biomejs/biome': false

patchedDependencies:
  '@hocuspocus/server@3.4.4': patches/@hocuspocus__server@3.4.4.patch
  '@better-auth/cimd@1.7.2': patches/@better-auth__cimd@1.7.2.patch
  '@better-auth/oauth-provider@1.7.2': patches/@better-auth__oauth-provider@1.7.2.patch
